import React, { PropsWithChildren, ReactNode } from 'react';
import { Layout as AntLayout, Menu, theme, Dropdown, MenuProps } from 'antd';
import { DownOutlined } from '@ant-design/icons';
import style from './index.module.css';
import menuList from '@/assets/data/menuList';
import Image from 'next/image';
import bookLogo from '@/assets/Image/book_logo.png'
import Head from 'next/head';
import { useRouter } from 'next/router';

const { Header, Sider, Content } = AntLayout;
const { managementList, userOption } = menuList

// export function Layout({ children }: { children: ReactNode }) {
export const Layout: React.FC<PropsWithChildren> = ({ children }) => {
    const router = useRouter();
    const handleMenuClick: MenuProps['onClick'] = ({ key }) => {
        router.push(key);
    }

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            <main>
                <AntLayout>
                    <Header className={style.header}>
                        <div className={style.logo}>
                            <Image src={bookLogo} width={40} height={40} alt="Book Logo" />
                            <p style={{ marginLeft: '10px' }}>图书管理系统</p>
                        </div>
                        <Dropdown menu={{ items: userOption }} >
                            <a onClick={(e) => e.preventDefault()}>
                                管理员
                                <DownOutlined rev={undefined} />
                            </a>
                        </Dropdown>
                    </Header>
                    <Content >
                        <AntLayout>
                            <Sider>
                                <Menu
                                    mode="inline"
                                    defaultSelectedKeys={['/book']}
                                    defaultOpenKeys={['book', 'borrow', 'user']}
                                    className={style.leftMenu}
                                    items={managementList}
                                    onClick={handleMenuClick}
                                />
                            </Sider>
                            <Content style={{ padding: '0 24px',paddingInline:'12px'}}>
                                {children}
                            </Content>
                        </AntLayout>
                    </Content>
                </AntLayout>
            </main>
        </>
    );
}